### PR TITLE
Compress PNGs with TinyPNG

### PR DESCRIPTION
**Pull request by paulschreiber**
Reduces PNGs from 8.5 MB to 7.3 MB.

### CODE REVIEW

**Comment by paulschreiber** [comment]
I reverted the changes to `third-party-libs`. Regarding `assets/banner-772x250.png`, can you elaborate? I don't see any differences.

**Comment by yo35** [comment]
Original image:
banner-772x250a

The one modified with TinyPNG:
banner-772x250b

You see the staircase effect in the background of the modified image?

**Comment by paulschreiber** [comment]
Oh, I see some banding. How odd! That seems like a TinyPNG bug.

**Comment by yo35** [comment]
Thanks to the fix relative to #117, the total size of the images has been reduced to 386 kB instead of about 7 MB, therefore I don't think we need additional size reduction (especially if this optimization requires lossy compression).

**Pull request closed without merging**
