### PR TITLE
Use yoda conditions

### PR DESCRIPTION
**Pull request by paulschreiber**
In some cases, replace large sets of `||` with `in_array()`.

### CODE REVIEW

**Comment by yo35** [comment]
OK for the yoda conditions. But why do you want to replace the `||` with `in_array(...)`? I've not checked, but I bet the `in_array(...)`-version is slower, as it requires a function call + an array instantiation. Also, I find the `in_array(...)`-version less readable (although I admit this is subjective).

**Comment by paulschreiber** [comment]
The `in_array()` code is shorter and easier to read and modify. Even if `in_array()` was theoretically slower, you'd have to profile in in a loop of 1000x or 10000x to observe any difference.

**Comment by yo35** [comment]
`$key === 'model' || $key === 'templateName' || $key === 'fileName'` => 67 characters
`in_array( $key, array( 'model', 'templateName', 'fileName' ), true )` => 69 characters

So the `is_array(...)` is not shorter, it's slower for sure, and as I mentioned, I'm not convinced at all by the "easier to read".

**Comment by paulschreiber** [comment]
The code is shorter when the list gets really long, like this:
```
- return ( $value === 'none' || $value === 'frame' || $value === 'above' || $value === 'below'
-    || $value === 'floatLeft' || $value === 'floatRight' || $value === 'scrollLeft' || $value === 'scrollRight' ) ? $value : null;
+ return ( in_array( $value, array( 'none', 'frame', 'above', 'below', 'floatLeft', 'floatRight', 'scrollLeft', 'scrollRight' ), true ) ) ? $value : null;
```

When you're reading the code with `in_array()`, you don't have to parse out every `||` operator and make sure there aren't any `&&`s mixed in, or any parentheses, which would affect the meaning/order of operations.

**Comment by paulschreiber** [comment]
I've resolved the merge conflicts here.

**Comment by yo35** [comment]
As I mentioned, I'm OK for the Yoda style, but I really don't want the `in_array(...)`.

**Comment by paulschreiber** [comment]
I've removed the in_array() calls.

**Comment by yo35** [comment]
Thanks.

**Pull request merged**
