### PR TITLE
Add build tools for PHPCS and eslint validation

### PR DESCRIPTION
**Pull request by paulschreiber**
This installs PHPCS, WPCS, eslint and Grunt, along with configuration files for validating the code.

I've ignore the `snake_case`-related rules because fixing them would be too risky at this point.

eslint:
* clean up whitespace in files
* remove jshint-related comments and .jshintrc
* add .eslintrc

### CODE REVIEW

**Comment by paulschreiber** [comment]
Can this be merged?

**Comment by yo35** [comment]
Standby for the moment (same reason as #112)

**Comment by paulschreiber** [comment]
I've added a grunt task to lint and minify the JavaScript.

**Comment by paulschreiber** [comment]
Added `grunt stats`.

**Comment by paulschreiber** [comment]
Added `grunt clean`.

**Comment by yo35** [comment]
Hi,
I'm not familiar with the grunt tool, so I read a few articles on the subject, among them:
https://www.keithcirkel.co.uk/why-we-should-stop-using-grunt/
https://blog.jcoglan.com/2014/02/05/building-javascript-projects-with-make/

I must say that, from what I read, I'm quite reluctant to use grunt.

I've added a `phpcs.xml` config file based on yours to the master (together with a `make phpcs` target to run it from the console). I have had to exclude a few rules for the moment, but the point is the phpcs report is now free of errors/warnings. It's should be possible now to progressively enlarge the set of enabled rules and to fix corresponding issues one by one.

**Comment by paulschreiber** [comment]
Yes, there are cranky people on the internet with four-year-old (bad) advice on build systems. Most modern web projects are using Grunt or Gulp.

Grunt is still very popular, and it's used by the WordPress core team:
https://make.wordpress.org/core/2018/03/28/grunt-patch-wordpress-1-0-0/

**Pull request closed without merging**
